### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by neizod** [neizod/extmath#11]
Anyone interest to release this module to PyPI? I have no experience doing it.

We may also need to change the name of the project first?

- [x] change repo name.
- [x] test build on Test PyPI.
- [x] release to PyPI.

**Comment by destag** [comment]
I can help you with this

**Comment by Pineapple6** [comment]
It would be great to fist release it to Test PyPI, check if everything is ok and then release it to the real PyPI.

**Comment by neizod** [comment]
@destag do I need more files in the repo?

@Pineapple6 never heard of that before, thx!

**Comment by destag** [comment]
@neizod You have to install [twine](https://pypi.org/project/twine/). Or use CI like Travis-CI to automate deployment.

**Comment by Pineapple6** [comment]
So, there it is :)
